CREATE TABLE PERSON(
	ID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	AGE INT(3) NOT NULL);

INSERT INTO PERSON values(NULL,'Michael','22');
INSERT INTO PERSON values(NULL,'Alex','23');
INSERT INTO PERSON values(NULL,'Kevin','19');

commit;